import JSZip from "jszip";
import { saveAs } from "file-saver";
import { ParsedFiles } from "./code-parser";

/**
 * Export the generated website as a ZIP file
 */
export async function exportAsZip(files: ParsedFiles, projectName: string = "website"): Promise<void> {
  const zip = new JSZip();
  
  // Create folder structure
  const srcFolder = zip.folder("src");
  const stylesFolder = zip.folder("styles");
  const scriptsFolder = zip.folder("scripts");
  
  // Add files
  if (srcFolder) {
    srcFolder.file("index.html", files.html);
  }
  
  if (stylesFolder && files.css) {
    stylesFolder.file("main.css", files.css);
  }
  
  if (scriptsFolder && files.js) {
    scriptsFolder.file("main.js", files.js);
  }
  
  // Create a standalone index.html at root that includes everything
  const standaloneHtml = createStandaloneHtml(files);
  zip.file("index.html", standaloneHtml);
  
  // Add a README
  const readme = `# ${projectName}

Generated by Surreal Sites AI Website Builder

## Project Structure

- \`index.html\` - Standalone HTML file (ready to open in browser)
- \`src/index.html\` - Main HTML structure
- \`styles/main.css\` - Extracted CSS styles
- \`scripts/main.js\` - Extracted JavaScript

## Usage

1. Open \`index.html\` in your browser to preview the website
2. Edit individual files as needed
3. For production, consider minifying CSS and JS

## Customization

Feel free to modify the code to suit your needs. The standalone index.html 
contains everything inline for easy deployment, while the separate files 
in folders are better for development.

---
Created with ❤️ by Surreal Sites
`;
  zip.file("README.md", readme);
  
  // Generate and download
  const blob = await zip.generateAsync({ type: "blob" });
  const filename = `${projectName.toLowerCase().replace(/\s+/g, "-")}-${Date.now()}.zip`;
  saveAs(blob, filename);
}

/**
 * Create a standalone HTML file with inline CSS and JS
 */
function createStandaloneHtml(files: ParsedFiles): string {
  // If the HTML already looks complete, return it
  if (files.html.includes("<!DOCTYPE>") || files.html.includes("<html")) {
    return files.html;
  }
  
  // Otherwise build a complete document
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Generated Website</title>
  <style>
${files.css || "/* No styles */"}
  </style>
</head>
<body>
${files.html}
  <script>
${files.js || "// No scripts"}
  </script>
</body>
</html>`;
}

/**
 * Export a single file
 */
export function exportFile(content: string, filename: string, mimeType: string = "text/plain"): void {
  const blob = new Blob([content], { type: mimeType });
  saveAs(blob, filename);
}
